schedule:
  - morning:
     imageFile: "./Homestar/cranky.png"
     startTime: "08:00AM"
     endTime: "10:00AM"
  - lunch:
     imageFile: "./Homestar/closed_mouth.png"
     startTime: "10:00AM"
     endTime: "2:30PM"
  - arvo:
     imageFile: "./Homestar/open_mouth.png"
     startTime: "2:30PM"
     endTime: "5:00PM"
  - evening:
     imageFile: "./Homestar/weary.png"
     startTime: "5:00PM"
     endTime: "8:00PM"
  - sleep:
     imageFile: "./Homestar/sleepy.png"
     startTime: "8:00PM"
     endTime: "06:00AM"
  - default:
      imageFile: "./Homestar/sleepy.png"
