schedule:
  - morning:
      imageFile: "./Homestar/cranky.png"
      startTime: "8:00"
      endTime: "10:00"
  - lunch:
      imageFile: "./Homestar/closed_mouth.png"
      startTime: "10:00"
      endTime: "14:30"
  - arvo:
      imageFile: "./Homestar/open_mouth.png"
      startTime: "14:30"
      endTime: "17:00"
  - evening:
      imageFile: "./Homestar/open_mouth.png"
      startTime: "17:00"
      endTime: "22:00"
  - overnight:
      imageFile: "./Homestar/open_mouth.png"
      startTime: "22:00"
      endTime: "06:00"
  - default:
      imageFile: "./Homestar/sleepy.png"