schedule:
  - morning:
     image: "./Homestar/cranky.png"
     endTime: "10:00AM"
  - lunch:
     image: "./Homestar/closed_mouth.png"
     endTime: "2:30PM"
  - arvo:
     image: "./Homestar/open_mouth.png"
     endTime: "5:00PM"
  - evening:
     image: "./Homestar/weary.png"
     endTime: "8:00PM"
  - sleep:
     image: "./Homestar/sleepy.png"
     endTime: "06:00AM"

